set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[0]]
set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[0]]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[1]]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[1]]
set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[2]]
set_property -dict { PACKAGE_PIN Y17   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[2]]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[3]]
set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[3]]

set_property -dict { PACKAGE_PIN W14   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[4]]
set_property -dict { PACKAGE_PIN Y14   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[4]]
set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[5]]
set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[5]]
set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[6]]
set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[6]]
set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports pwmout_A_0[7]]
set_property -dict { PACKAGE_PIN P16   IOSTANDARD LVCMOS33 } [get_ports pwmout_B_0[7]]

set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports interrupt_0]

#set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports IO1_1N]
#set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports IO1_1P]
#set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports gpio_io_o_0[0]]
#set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports gpio_io_o_0[1]]
#set_property -dict { PACKAGE_PIN Y17   IOSTANDARD LVCMOS33 } [get_ports gpio_io_o_0[2]]
#set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33 } [get_ports IO1_4N]
#set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 }  [get_ports IO2_1N]
#set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 }  [get_ports IO2_1P]
#set_property -dict { PACKAGE_PIN Y17   IOSTANDARD LVCMOS33 }  [get_ports IO3_1N]
#set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 }  [get_ports IO3_1P]